### ISSUE TITLE
go test always in current directory

### ISSUE THREAD

**Issue by mattkanwisher** [vcastellm/guard-go#3]
It seems like guard-go always runs the tests "Dir.pwd" doesn't seem to be a way to override this? If so I'll make a patch

**Comment by vcastellm** [comment]
Your patch will be very wellcome.

On Thu, Feb 14, 2013 at 7:29 PM, Matthew Kanwisher <notifications@github.com

> wrote:
> 
> It seems like guard-go always runs the tests "Dir.pwd" doesn't seem to be
> a way to override this? If so I'll make a patch
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/victorcoder/guard-go/issues/3.

## 

_Do Androids Dream of Electric Sheep?_
@victorcoder

**Comment by vcastellm** [comment]
Reopen in case of PR
